SystemOrganization addCategory: #MyNewLaserGame!
SystemOrganization addCategory: #'MyNewLaserGame-Directions'!
SystemOrganization addCategory: #'MyNewLaserGame-Examples - Board Game'!
SystemOrganization addCategory: #'MyNewLaserGame-Examples - Buttons'!
SystemOrganization addCategory: #'MyNewLaserGame-Examples - CellElement'!
SystemOrganization addCategory: #'MyNewLaserGame-Examples - ControlPanelElement'!
SystemOrganization addCategory: #'MyNewLaserGame-Examples - GridElement'!
SystemOrganization addCategory: #'MyNewLaserGame-Graphics-Buttons'!
SystemOrganization addCategory: #'MyNewLaserGame-Graphics-Cells'!
SystemOrganization addCategory: #'MyNewLaserGame-Graphics-Game'!
SystemOrganization addCategory: #'MyNewLaserGame-Graphics-Grid'!
SystemOrganization addCategory: #'MyNewLaserGame-Laser'!
SystemOrganization addCategory: #'MyNewLaserGame-LaserGame'!
SystemOrganization addCategory: #'MyNewLaserGame-Model'!
SystemOrganization addCategory: #'MyNewLaserGame-Tests'!
